# Generated by Django 3.2.12 on 2022-04-04 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_request', models.CharField(max_length=20, verbose_name='เลขคำร้องจากระบบ')),
                ('no_enterprise', models.CharField(blank=True, max_length=30, null=True, verbose_name='เลขหนังสือ สปก.')),
                ('no_ocsb', models.CharField(blank=True, max_length=30, null=True, verbose_name='เลขอนุญาต สอน.')),
                ('is_season', models.BooleanField(verbose_name='ในฤดูการผลิตหรือไม่')),
                ('total_syrup', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True, verbose_name='ปริมาณน้ำเชื่อม Syrub (ตัน)')),
                ('total_bmolasses', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True, verbose_name='ปริมาณน้ำเชื่อม B-molasses (ตัน)')),
                ('total_cmolasses', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True, verbose_name='ปริมาณน้ำเชื่อม C-molasses (ตัน)')),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='ปริมาณน้ำเชื่อมรวมทั้งหมด (ตัน)')),
                ('total_usage_syrup', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True, verbose_name='ปริมาณน้ำเชื่อม Syrub (ตัน)[ใช้แล้ว]')),
                ('total_usage_bmolasses', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True, verbose_name='ปริมาณน้ำเชื่อม B-molasses (ตัน)[ใช้แล้ว]')),
                ('total_usage_cmolasses', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True, verbose_name='ปริมาณน้ำเชื่อม C-molasses (ตัน)[ใช้แล้ว]')),
                ('date_request', models.DateField(blank=True, null=True, verbose_name='วันที่ขออนุญาตฯ')),
                ('date_inspect', models.DateField(blank=True, null=True, verbose_name='วันที่บันทึกรับแจ้ง')),
                ('date_visit', models.DateField(blank=True, null=True, verbose_name='วันที่บันทึกตรวจสถานที่')),
                ('date_approve', models.DateField(blank=True, null=True, verbose_name='วันที่อนุมัติ')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='วันเวลาที่สร้างข้อมูล')),
                ('workflow_state', django_fsm.FSMIntegerField(choices=[(0, 'Draft'), (1, 'Review'), (2, 'Site Visit'), (3, 'Approval'), (4, 'Accept'), (5, 'Reject'), (6, 'Close')], default=0, help_text='work flow state')),
                ('file_request', models.FileField(blank=True, null=True, upload_to='documents/quota/request/', verbose_name='หนังสือขออนุญาต สถานประกอบการ')),
                ('file_sitevisit', models.FileField(blank=True, null=True, upload_to='documents/quota/sitevisit/', verbose_name='หนังสือประสานคณะทำงานฯ ร่วมลงพื้นที่ตรวจสอบ')),
                ('file_survey', models.FileField(blank=True, null=True, upload_to='documents//quota/survey/', verbose_name='แบบตรวจสอบกระบวนการส่งถ่ายน้ำเชื่อมฯ')),
                ('file_approve', models.FileField(blank=True, null=True, upload_to='documents//quota/approve/', verbose_name='หนังสืออนุญาตฯ')),
                ('enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_base.enterprise', verbose_name='สถานประกอบการ')),
                ('purchasers', models.ManyToManyField(blank=True, to='app_base.Purchaser', verbose_name='โรงงานรับซื้อน้ำเชื่อมฯ')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_base.season', verbose_name='ฤดูกาลผลิตที่ขออนุญาตฯ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึกคำร้อง')),
            ],
            options={
                'verbose_name': 'QuotaRequest',
                'verbose_name_plural': 'QuotaRequests',
                'db_table': '',
                'ordering': ['-date_request', 'season', '-no_request'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SyrupUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_report', models.DateField(verbose_name='วันที่รายงาน')),
                ('syrup_weight', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='น้ำหนัก/ปริมาณน้ำเชื่อม (ตัน)')),
                ('syrup_type', models.SmallIntegerField(choices=[(1, 'Syrup'), (2, 'B-molasses'), (3, 'C-molasses')], verbose_name='ชนิดของน้ำเชื่อม')),
                ('theoretical', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Actual to Theoretical Recovery')),
                ('undetermine_loss', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ร้อยละของการสูญเสียโดยไม่ทราบสาเหตุ')),
                ('daily_cane_input', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='ปริมาณอ้อยทั้งหมดที่เข้าหีบประจำวัน (ตัน)')),
                ('pol_in_can', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ร้อยละของค่าโพลในอ้อย')),
                ('pol_extraction', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ร้อยละของ Pol Extraction')),
                ('loss_filter_cake', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ร้อยละของการสูญเสียน้ำตาลในกากตะกอนกรอง')),
                ('syrup_brix', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='ค่าบริกซ์น้ำเชื่อม')),
                ('syrup_pol', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='ค่าโพลน้ำเชื่อม')),
                ('syrup_purity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ความบริสุทธิ์ของน้ำเชื่อม')),
                ('rawsugar_pol', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='ค่าโพลน้ำตาลทรายดิบ')),
                ('rawsugar_moisture', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='ค่าความชื้นน้ำตาลทรายดิบ')),
                ('rawsugar_purity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ความบริสุทธิ์น้ำตาลทรายดิบ')),
                ('mollasses_brix', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='ค่าบริกซ์กากน้ำตาล')),
                ('mollasses_pol', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='ค่าโพลกากน้ำตาล')),
                ('mollasses_purity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ความบริสุทธิ์ของกากน้ำตาล')),
                ('density_indice', models.DecimalField(decimal_places=5, default=0, max_digits=7, verbose_name='ดัชนีความหนาแน่น')),
                ('syrup_valume', models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='ปริมาณน้ำเชื่อมที่ผลิตเป็นเอทานอล (ลบ.ม.)')),
                ('sjm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='น้ำตาลที่ควรจะผลิตได้ในรูป S-J-M')),
                ('actual_sugar_recovery', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Actual Sugar Recovery')),
                ('raw_sugar_tons_pol', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Raw Sugar (Tons Pol)')),
                ('raw_sugar_tons', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ปริมาณน้ำตาลทรายดิบที่ผลิตได้/Raw Sugar (Tons)')),
                ('workflow_state', django_fsm.FSMIntegerField(choices=[(0, 'รอส่งข้อมูล'), (1, 'รอยืนยัน จนท.บริษัท'), (2, 'รอยืนยัน สอน. ประจำโรงงาน'), (3, 'รอยืนยัน จนท. เขต'), (4, 'รอยืนยัน จนท. สบน.'), (5, 'รอยืนยัน จนท. กสช.'), (6, 'ผ่านการยืนยัน'), (7, 'ไม่ผ่าน')], default=0, help_text='work flow state')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='วันที่บันทึก')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานหรือไม่')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.enterprise', verbose_name='โรงงานที่ได้รับอนุญาต')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.purchaser', verbose_name='โรงงานรับซื้อ')),
                ('quota_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ocsb.quotarequest', verbose_name='คำร้องขออนุญาตฯ')),
            ],
            options={
                'verbose_name': 'SyrupUsage',
                'verbose_name_plural': 'SyrupUsages',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
