# Generated by Django 3.2.12 on 2022-04-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ocsb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotarequest',
            name='season_round',
            field=models.IntegerField(blank=True, null=True, verbose_name='รอบที่ขออนุญาตฯ'),
        ),
        migrations.AlterField(
            model_name='quotarequest',
            name='is_season',
            field=models.BooleanField(blank=True, null=True, verbose_name='ในฤดูการผลิตหรือไม่'),
        ),
    ]
