# Generated by Django 3.2.12 on 2022-04-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ocsb', '0002_auto_20220405_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotarequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ใช้งานหรือไม่'),
        ),
    ]
