# Generated by Django 3.2.12 on 2022-04-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ocsb', '0003_quotarequest_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='syrupusage',
            name='ton_pol_rawsuger',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Ton Pol Raw Sugar'),
        ),
        migrations.AddField(
            model_name='syrupusage',
            name='ton_pol_syrup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Ton Pol Syrup'),
        ),
        migrations.AddField(
            model_name='syrupusage',
            name='ton_under_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Ton Undetermine Loss'),
        ),
    ]
