# Generated by Django 3.2.12 on 2022-04-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ocsb', '0004_auto_20220407_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='syrupusage',
            name='ton_mollasses',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Ton Mollasses (Tons)'),
        ),
        migrations.AddField(
            model_name='syrupusage',
            name='ton_pol_mollasses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Ton Pol  Mollasses'),
        ),
    ]
