# Generated by Django 3.2.12 on 2022-04-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ocsb', '0005_auto_20220407_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='syrupusage',
            name='ratio_raw_cane',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Ratio of Raw Syup per Cane'),
        ),
        migrations.AddField(
            model_name='syrupusage',
            name='ton_pol_clearified',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Ton Pol Clearified Juice'),
        ),
        migrations.AddField(
            model_name='syrupusage',
            name='ton_pol_daily',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Ton Pol Daily Cane Input '),
        ),
        migrations.AddField(
            model_name='syrupusage',
            name='ton_pol_filter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Ton Pol Filter Cake'),
        ),
        migrations.AddField(
            model_name='syrupusage',
            name='ton_pol_mixed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Ton Pol Mixed Juice'),
        ),
        migrations.AddField(
            model_name='syrupusage',
            name='ton_raw_syrup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Ton Raw Syrup'),
        ),
    ]
