# Generated by Django 3.2.12 on 2022-04-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ocsb', '0006_auto_20220407_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='syrupusage',
            name='diff_raw_sugar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='ส่วนต่าง Raw Sugar (Tons) (สอน.-บริษัท)'),
        ),
        migrations.AddField(
            model_name='syrupusage',
            name='diff_ton_mollasses',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='ส่วนต่าง Ton Mollasses (Tons) (สอน.-บริษัท)'),
        ),
        migrations.AddField(
            model_name='syrupusage',
            name='efficiency_mollasses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='ประสิทธิภาพการผลิตกากน้ำตาล กก/ตันอ้อย'),
        ),
        migrations.AddField(
            model_name='syrupusage',
            name='efficiency_raw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='ประสิทธิภาพการผลิตน้ำตาล กก/ตันอ้อย'),
        ),
        migrations.AddField(
            model_name='syrupusage',
            name='estimate_ton_can',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Estimated Ton Cane Using as Raw '),
        ),
        migrations.AddField(
            model_name='syrupusage',
            name='raw_sugar_tons_ent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='บริษัทคำนวณ Raw Sugar (Tons)'),
        ),
        migrations.AddField(
            model_name='syrupusage',
            name='ton_mollasses_ent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='บริษัทคำนวณ Ton Mollasses (Tons)'),
        ),
        migrations.AlterField(
            model_name='syrupusage',
            name='ton_pol_daily',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Ton Pol Daily Cane Input'),
        ),
    ]
