# Generated by Django 3.2.12 on 2022-04-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ocsb', '0007_auto_20220407_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotarequest',
            name='is_season',
            field=models.BooleanField(default=0, verbose_name='ในฤดูการผลิตหรือไม่'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='syrupusage',
            name='raw_sugar_tons',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='ปริมาณน้ำตาลทรายดิบที่ผลิตได้/Raw Sugar (Tons)'),
        ),
        migrations.AlterField(
            model_name='syrupusage',
            name='raw_sugar_tons_ent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='บริษัทคำนวณ Raw Sugar (Tons)'),
        ),
        migrations.AlterField(
            model_name='syrupusage',
            name='syrup_valume',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='ปริมาตรน้ำเชื่อม (ลบ.ม.)'),
        ),
    ]
