# Generated by Django 3.2.12 on 2022-04-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ocsb', '0008_auto_20220410_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotarequest',
            name='file_approve',
            field=models.FileField(blank=True, null=True, upload_to='documents/quota/approve/', verbose_name='หนังสืออนุญาตฯ'),
        ),
        migrations.AlterField(
            model_name='quotarequest',
            name='file_survey',
            field=models.FileField(blank=True, null=True, upload_to='documents/quota/survey/', verbose_name='แบบตรวจสอบกระบวนการส่งถ่ายน้ำเชื่อมฯ'),
        ),
    ]
