# Generated by Django 3.2.12 on 2022-04-04 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amphur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='รหัสอำเภอ')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่ออำเภอ')),
                ('postcode', models.CharField(max_length=20, verbose_name='รหัสไปรษณีย์')),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสถานประกอบการ')),
                ('address_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขที่')),
                ('mu', models.CharField(blank=True, max_length=100, null=True, verbose_name='หมู่')),
                ('soi', models.CharField(blank=True, max_length=100, null=True, verbose_name='ซอย')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='ถนน')),
                ('postcode', models.CharField(blank=True, max_length=200, null=True, verbose_name='รหัสไปรษณีย์')),
                ('tel', models.CharField(blank=True, max_length=200, null=True, verbose_name='เบอร์ติดต่อ')),
                ('fax', models.CharField(blank=True, max_length=200, null=True, verbose_name='แฟกซ์ติดต่อ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมลติดต่อ')),
                ('website', models.CharField(blank=True, max_length=200, null=True, verbose_name='เว็บไซต์ติดต่อ')),
                ('amphur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_base.amphur')),
            ],
            options={
                'verbose_name': 'Enterprise',
                'verbose_name_plural': 'Enterprises',
            },
        ),
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อโรงงาน')),
                ('factory_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสโรงงานรับซื้อ')),
            ],
            options={
                'verbose_name': 'Purchaser',
                'verbose_name_plural': 'Purchasers',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อภูมิภาค')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='ชื่อฤดูกาล')),
                ('code', models.CharField(max_length=6, null=True, verbose_name='รหัสย่อ')),
                ('is_active', models.BooleanField(default=True, verbose_name='สถานะ')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='Tumbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='รหัสตำบล')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อตำบล')),
                ('amphur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_base.amphur')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='รหัสจังหวัด')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อจังหวัด')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_base.region')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขที่')),
                ('mu', models.CharField(blank=True, max_length=100, null=True, verbose_name='หมู่')),
                ('soi', models.CharField(blank=True, max_length=100, null=True, verbose_name='ซอย')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='ถนน')),
                ('postcode', models.CharField(blank=True, max_length=200, null=True, verbose_name='รหัสไปรษณีย์')),
                ('tel', models.CharField(blank=True, max_length=200, null=True, verbose_name='เบอร์ติดต่อ')),
                ('amphur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_base.amphur')),
                ('enterprises', models.ManyToManyField(blank=True, to='app_base.Enterprise', verbose_name='โรงงานที่รับผิดชอบ')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_base.province')),
                ('tumbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_base.tumbol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='อ้างอิงโมเดล User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.AddField(
            model_name='enterprise',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_base.province'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='tumbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_base.tumbol'),
        ),
        migrations.AddField(
            model_name='amphur',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_base.province'),
        ),
    ]
