# Generated by Django 3.2.12 on 2022-04-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0002_brix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brix',
            name='brix_value',
            field=models.DecimalField(decimal_places=1, max_digits=4, unique=True, verbose_name='ค่าบริกซ์'),
        ),
    ]
